name: youtube_notes_flutter
description: A Flutter app to take timestamped and handwritten notes for YouTube videos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  flutter_drawing_board: ^0.3.0
  pdf: ^3.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/
